
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/02_fully_connected.ipynb


# In the course, Jeremy builds on top of previous notebooks by importing them
# Since we are storing previous files in Drive, synced with git, this is a workaround to import them
# ref: https://stackoverflow.com/questions/4383571/importing-files-from-different-folder

import sys
import math
sys.path.insert(1, '/content/drive/MyDrive/git/fast-ai-part2/exp/')
from nb_01 import *

def get_data():
  path = datasets.download_data(MNIST_URL, ext = '.gz')
  with gzip.open(path, 'rb') as f:
    ((x_train, y_train), (x_valid, y_valid), _) = pickle.load(f, encoding = 'latin-1')
  return map(tensor, (x_train, x_valid, y_train, y_valid))

def normalize(x,m,s): return (x-m)/s

def test_near_zero(a, atol = 1e-03): assert abs(a)<atol, f"{a}:Near Zero"

# Covered initialization. So can use pytorch init.
from torch.nn import init

def mse(output, target): return ((output.squeeze(1) - target)**2).mean()

from torch import nn