
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/01_matmul_broadcast.ipynb

import operator

def test(a, b, cmp, cname=None):
  if cname is None: cname = cmp.__name__
  assert cmp(a, b), f"{cname}:\n{a}\n{b}"

def test_eq(a, b): test(a, b, operator.eq, "==")

from fastai import datasets
import pickle, gzip
import matplotlib as mpl
from matplotlib import pyplot as plt
from torch import tensor
import torch

MNIST_URL='https://github.com/mnielsen/neural-networks-and-deep-learning/blob/master/data/mnist.pkl.gz?raw=true'

def near(a,b): return(torch.allclose(a,b,rtol=1e-05))
def test_near(a,b): assert(near(a,b))